build_mobile_task:
  container:
    dockerfile: ci/Dockerfile
    cpu: 2.6
    memory: 2660Mi
    use_in_memory_disk: true
  environment:
    USERNAME: ENCRYPTED[816e19d5ad8f8cb65915a18048a3e7e122e7a13cfb7137932eab0cff57624b672bf31199c120b5db0e1120859f1ce248]
    PASSWORD: ENCRYPTED[4d2ba7c7bb380bbae1b970425dce4894dd1374fcad067c4a68d4a93cd123b0f9b00d37f047b708d3b852873044c025b5]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  login_script: expo login -u $USERNAME -p $PASSWORD --non-interactive
  build_script: |
    expo build:android --release-channel dev --config ./app.json --no-wait
    uptime

publish_web_task:
  container:
    dockerfile: ci/Dockerfile
    cpu: 2
    memory: 4G
    use_in_memory_disk: true
  environment:
    USERNAME: ENCRYPTED[816e19d5ad8f8cb65915a18048a3e7e122e7a13cfb7137932eab0cff57624b672bf31199c120b5db0e1120859f1ce248]
    PASSWORD: ENCRYPTED[4d2ba7c7bb380bbae1b970425dce4894dd1374fcad067c4a68d4a93cd123b0f9b00d37f047b708d3b852873044c025b5]
    CONFIG: ENCRYPTED[51f7c788c0663eaf8fd0de2638452ddb5fb5565febc8df3f526022ed304294b0295171f210c004e29946aa79a2da4f62]
    TOKEN: ENCRYPTED[ceaf370b4f3962acabf75f17745ba3467b4c45f1c897a8331f0c2c8aa0ee963112dc696c6820dc543a8de4e72c05118c]
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm install
  web_build_cache:
    folder: .expo/web/cache
    fingerprint_script: cat package-lock.json
  login_script: expo login -u $USERNAME -p $PASSWORD --non-interactive
  build_web_script: expo build:web
  publish_to_vercel_script: |
    mkdir .vercel
    echo $CONFIG >> .vercel/project.json
    vercel -t $TOKEN --confirm

